FROM python:3.7.2-stretch

ENV IMAGE_TAG ${IMAGE_TAG}

COPY main/ /srv/www/web-crawler
COPY cluster-templates/ /srv/www/web-crawler/cluster-templates/
COPY cluster-setup/kube_setup /srv/www/web-crawler

WORKDIR /srv/www/web-crawler

RUN apt-get update \
  && apt-get install nano -y

RUN pip install --no-cache-dir -r requirements.txt \
  && ./kube_setup \
  && mv kubeconfig $HOME/.kube/config
#  && helm init --service-account tiller

EXPOSE 8001

CMD ["python", "project/manage.py", "runserver", "0.0.0.0:8001"]