FROM python:3.7.2-stretch

ARG IMAGE_TAG
ENV IMAGE_TAG=$IMAGE_TAG

COPY crawler-manager/ /srv/www/web-crawler
COPY cluster-templates/ /srv/www/web-crawler/cluster-templates/
COPY cluster-setup/kube_setup /srv/www/web-crawler

WORKDIR /srv/www/web-crawler

RUN apt-get update \
  && apt-get install nano redis-server -y

RUN pip install --no-cache-dir -r requirements.txt \
  && ./kube_setup \
  && mv kubeconfig $HOME/.kube/config

EXPOSE 8002

CMD service redis-server start && tail -f app.py
# CMD service redis-server start && python app.py
