FROM joyzoursky/python-chromedriver:3.7
COPY creds/ /creds
COPY crawler/ /srv/www/web-crawler

WORKDIR /srv/www/web-crawler

RUN cp /usr/local/bin/chromedriver /srv/www/web-crawler
RUN pip install --no-cache-dir -r requirements.txt

ENV GCS_BUCKET="cscie-599-spring-2019-web-crawler"
ENV GOOGLE_APPLICATION_CREDENTIALS="/creds/WebCrawler-feb11a08e450.json"

EXPOSE 8003

CMD ["python" , "app.py"]
