FROM python:3.7.2-stretch

COPY creds/ /creds
COPY crawler/ /srv/www/web-crawler

WORKDIR /srv/www/web-crawler
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

# install chromedriver
RUN apt-get install -yqq unzip
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /srv/www/web-crawler

RUN pip install --no-cache-dir -r requirements.txt

ENV GCS_BUCKET="cscie-599-spring-2019-web-crawler"
ENV GOOGLE_APPLICATION_CREDENTIALS="/creds/WebCrawler-feb11a08e450.json"

EXPOSE 8003

CMD ["python" , "app.py"]
