# Generated by Django 2.1.7 on 2019-03-17 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'All content from a single domain'), (2, 'Content from multiple URLs')], default=1, verbose_name='crawl type')),
                ('domain', models.URLField(blank=True, default='', max_length=500)),
                ('urls', models.TextField(blank=True, default='', max_length=1000)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('created', models.DateTimeField(editable=False, verbose_name='crawl request creation time')),
                ('modified', models.DateTimeField(verbose_name='crawl request modification time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_requests_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
