# Generated by Django 2.1.7 on 2019-03-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='docs_all',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='docs_docx',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='docs_html',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='docs_pdf',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='docs_txt',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='docs_xml',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
