# Generated by Django 2.1.7 on 2019-03-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190317_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='docs_collected',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'In progress'), (3, 'Finished'), (4, 'Failed')], default=1, verbose_name='crawl status'),
        ),
    ]
