# Generated by Django 2.1.7 on 2019-05-07 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'All content from a single domain'), (2, 'Content from multiple URLs')], default=1, verbose_name='crawl type')),
                ('domain', models.URLField(blank=True, default='', max_length=500)),
                ('urls', models.TextField(blank=True, default='', max_length=1000)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('docs_all', models.BooleanField(blank=True, default=False)),
                ('docs_html', models.BooleanField(blank=True, default=False)),
                ('docs_docx', models.BooleanField(blank=True, default=False)),
                ('docs_pdf', models.BooleanField(blank=True, default=False)),
                ('docs_xml', models.BooleanField(blank=True, default=False)),
                ('docs_txt', models.BooleanField(blank=True, default=False)),
                ('docs_collected', models.PositiveIntegerField(blank=True, default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'In progress'), (3, 'Finished'), (4, 'Failed')], default=1, verbose_name='crawl status')),
                ('storage_location', models.URLField(blank=True, default='', max_length=1000)),
                ('crawler_manager_endpoint', models.URLField(blank=True, default='', max_length=500)),
                ('manifest', models.URLField(blank=True, default='', max_length=1000)),
                ('num_crawlers', models.PositiveIntegerField(default=1, verbose_name='Number crawler instances')),
                ('created', models.DateTimeField(editable=False, verbose_name='crawl request creation time')),
                ('modified', models.DateTimeField(verbose_name='crawl request modification time')),
                ('model_labels', models.CharField(blank=True, max_length=128)),
                ('crawl_library', models.PositiveSmallIntegerField(choices=[(1, 'Selenium'), (2, 'Python Library')], default=1, verbose_name='crawl library')),
                ('docs_uploaded', models.PositiveIntegerField(blank=True, default=0)),
                ('num_crawl_pages_limit', models.PositiveIntegerField(blank=True, default=100)),
                ('crawl_time', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('labels', models.TextField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(editable=False, verbose_name='model creation time')),
                ('modified', models.DateTimeField(verbose_name='model modification time')),
                ('storage_location', models.URLField(blank=True, default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_bucket', models.URLField(blank=True, default='', max_length=500, verbose_name='Storage Bucket')),
                ('api_key', models.CharField(max_length=512, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=512, verbose_name='API Secret')),
                ('num_crawlers', models.PositiveIntegerField(default=1, verbose_name='Number crawler instances')),
                ('created', models.DateTimeField(editable=False, verbose_name='profile creation time')),
                ('modified', models.DateTimeField(verbose_name='profile modification time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='model',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_requests_model', to='main_app.MlModel'),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_requests_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
