# Generated by Django 2.1.7 on 2019-04-30 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='model_name',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='model',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='crawl_requests_model', to='main_app.MlModel'),
        ),
    ]
