# Generated by Django 2.1.7 on 2019-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='crawler_manager_endpoint',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='manifest',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='crawlrequest',
            name='s3_location',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
