# Generated by Django 2.1.7 on 2019-04-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190408_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='num_crawlers',
            field=models.PositiveIntegerField(default=1, verbose_name='Number crawler instances'),
        ),
    ]
