# Generated by Django 2.1.7 on 2019-04-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190429_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='model',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_requests_model', to='main_app.MlModel'),
        ),
    ]
