# Generated by Django 2.1.7 on 2019-04-27 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_crawlrequest_num_crawlers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('labels', models.TextField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(editable=False, verbose_name='model creation time')),
                ('modified', models.DateTimeField(verbose_name='model modification time')),
                ('s3_location', models.URLField(blank=True, default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
