# Generated by Django 2.1.7 on 2019-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190429_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='crawl_library',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Selenium'), (2, 'Python Library')], default=1, verbose_name='crawl library'),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='docs_uploaded',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='num_crawl_pages_limit',
            field=models.PositiveIntegerField(blank=True, default=100),
        ),
    ]
