# Generated by Django 2.1.7 on 2019-04-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_mlmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='model_labels',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='model_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
