# Generated by Django 2.1.7 on 2019-05-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190505_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='crawl_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
